# Generated by Django 5.1.1 on 2025-07-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
