# Generated by Django 5.1.1 on 2025-07-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.CharField(max_length=20),
        ),
    ]
