# Generated by Django 5.1.1 on 2025-07-30 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_vehicle_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.student'),
        ),
    ]
