# Generated by Django 5.1.1 on 2025-07-30 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_userprofile_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.vehicle'),
        ),
        migrations.AlterField(
            model_name='student',
            name='trip_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
