# Generated by Django 5.1.1 on 2025-08-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_vehiclelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='ride_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='ride_stop',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
