# Generated by Django 5.1.1 on 2025-08-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_vehiclelocation_ride_start_vehiclelocation_ride_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], default='stopped', max_length=10),
        ),
    ]
