# Generated by Django 5.1.1 on 2025-08-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_vehiclelocation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='school',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='vehicle',
        ),
        migrations.CreateModel(
            name='StudentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=10)),
                ('trip_number', models.IntegerField()),
                ('route_order', models.PositiveIntegerField(help_text='Order of pickup/drop in the route')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.vehicle')),
            ],
            options={
                'unique_together': {('student', 'shift', 'trip_number')},
            },
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
