# Generated by Django 5.1.1 on 2025-08-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_shift_school_remove_shift_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='home_lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='home_lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
