# Generated by Django 5.1.1 on 2025-08-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_student_home_lat_student_home_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='trip_number',
        ),
        migrations.RemoveField(
            model_name='studentroute',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='studentroute',
            name='longitude',
        ),
    ]
