# Generated by Django 5.1.1 on 2025-08-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_student_trip_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='home_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
