# Generated by Django 5.1.1 on 2025-08-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_student_home_lat_alter_student_home_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
